//! Acceptance tests for `modhash-cli` (phase P18).
//!
//! The dedup ground-truth test below is the plan's verify clause: a
//! synthesized directory whose cluster labels are known by construction
//! must come back with exactly those labels. Everything is generated by
//! `modhash_cli::fixture` (SplitMix64-seeded), so the run is identical
//! on every platform and no fixture files are needed.

use std::path::PathBuf;

use modhash_cli::{
    DedupReport, Input, dedup_inputs, distance, fixture, render_description, signature_of,
};

fn input(name: &str, bytes: Vec<u8>) -> Input {
    Input {
        path: PathBuf::from(name),
        bytes,
    }
}

/// Sorts each cluster's members and the cluster list so equality is
/// label-for-label, not order-for-order.
fn normalize(report: &DedupReport) -> Vec<Vec<usize>> {
    let mut groups: Vec<Vec<usize>> = report
        .groups
        .iter()
        .map(|g| {
            let mut m = g.members.clone();
            m.sort_unstable();
            m
        })
        .collect();
    groups.sort_unstable();
    groups
}

/// Four base images × three perturbed variants = 12 inputs, four known
/// clusters. The clusters are known because the generator makes them:
/// bases differ in their low-frequency content (observed pairwise
/// distances 16..38), variants perturb pixels within ±4 (observed
/// distances 0..4), so only same-seed members sit inside the image
/// advisory bound (hamming ≤ 10).
#[test]
fn dedup_recovers_ground_truth_clusters() {
    let seeds = [0xA1u64, 0xA2, 0xA3, 0xA4];
    let mut inputs: Vec<Input> = Vec::new();
    // Interleave bases and variants so input order is not cluster order.
    for variant in 0..3u64 {
        for &seed in &seeds {
            let base = fixture::patterned_pixels(seed, 48, 40);
            let px = if variant == 0 {
                base
            } else {
                fixture::perturb_pixels(&base, seed ^ (variant << 8), 4, 997 + variant)
            };
            let bmp = fixture::bmp24(48, 40, &px);
            inputs.push(input(&format!("s{seed:#x}_v{variant}.bmp"), bmp));
        }
    }
    assert_eq!(inputs.len(), 12);

    let report = dedup_inputs(&inputs, None);
    assert!(
        report.skipped.is_empty(),
        "all inputs must sign: {:?}",
        report.skipped
    );
    assert!(report.singles.is_empty(), "no singles expected");
    assert_eq!(report.groups.len(), 4, "want 4 clusters, got {report:?}");

    // Ground truth: input i = variant (i/4) of seed seeds[i % 4].
    let mut want: Vec<Vec<usize>> = seeds
        .iter()
        .enumerate()
        .map(|(si, _)| (0..12).filter(|&i| i % 4 == si).collect())
        .collect();
    want.sort_unstable();
    assert_eq!(normalize(&report), want, "clusters must match ground truth");

    // Perturbed variants are *not* byte-identical, so groups are
    // perceptual, not exact — the exact flag must honestly say so.
    for g in &report.groups {
        assert!(!g.exact, "perturbed variants must not read as exact");
    }
}

/// The `--threshold` seam: at `distance == threshold` the pair still
/// clusters (inclusive bound); one tick below it does not. This is the
/// predicate `calibrate`'s output feeds.
#[test]
fn dedup_threshold_is_inclusive() {
    // Two patterned bases at a known distance apart.
    let a = fixture::bmp24(48, 40, &fixture::patterned_pixels(0xA1, 48, 40));
    let b = fixture::bmp24(48, 40, &fixture::patterned_pixels(0xA2, 48, 40));
    let sa = signature_of(&a).unwrap();
    let sb = signature_of(&b).unwrap();
    let d = distance(&sa, &sb).unwrap();
    assert!(d > 10, "two distinct bases must exceed the advisory bound");

    let inputs = vec![input("a.bmp", a), input("b.bmp", b)];
    let at = dedup_inputs(&inputs, Some(d));
    assert_eq!(at.groups.len(), 1, "d <= d must cluster (inclusive)");
    assert_eq!(at.groups[0].members, vec![0, 1]);

    let below = dedup_inputs(&inputs, Some(d - 1));
    assert!(below.groups.is_empty(), "d > d-1 must not cluster");
    assert_eq!(below.singles, vec![0, 1]);
}

/// Refused inputs (pending lanes, corrupt containers) land in
/// `skipped` — the report never silently drops a file.
#[test]
fn dedup_reports_skipped_inputs() {
    let mut mp4 = vec![0, 0, 0, 0x20];
    mp4.extend_from_slice(b"ftypisom");
    mp4.extend_from_slice(&[0; 24]);
    let img = fixture::bmp24(8, 8, &fixture::patterned_pixels(0xB1, 8, 8));
    let inputs = vec![
        input("one.bmp", img.clone()),
        input("clip.mp4", mp4),
        input("two.bmp", img),
    ];
    let report = dedup_inputs(&inputs, None);
    assert_eq!(report.skipped, vec![1], "the pending mp4 must be skipped");
    assert_eq!(report.groups.len(), 1, "the two identical bmps cluster");
    assert!(report.groups[0].exact, "identical bytes are exact dupes");
}

/// Binary lane: byte-identical files cluster; a 4 KiB-prefix shift
/// still clusters via content-defined chunking; an unrelated blob is a
/// single.
#[test]
fn dedup_binary_lane() {
    let blob = fixture::binary_blob(0xBEEF, 96 * 1024);
    let mut shifted = vec![0xAA; 4096];
    shifted.extend_from_slice(&blob);
    let other = fixture::binary_blob(0xFACE, 96 * 1024);
    let inputs = vec![
        input("a.bin", blob.clone()),
        input("b.bin", blob),
        input("c.bin", shifted),
        input("d.bin", other),
    ];
    let report = dedup_inputs(&inputs, None);
    assert_eq!(report.groups.len(), 1, "the three related blobs cluster");
    assert_eq!(normalize(&report), vec![vec![0, 1, 2]]);
    assert_eq!(report.singles, vec![3]);
}

/// `describe` must show all three tiers on every modality — the plan's
/// describe contract. The facade prints image tier-3 itself; the CLI
/// adds the explicit `tier3:` row for the other modalities.
#[test]
fn describe_output_lists_three_tiers() {
    let cases: Vec<(&str, Vec<u8>, &str)> = vec![
        (
            "image",
            fixture::bmp24(48, 40, &fixture::patterned_pixels(0xC1, 48, 40)),
            "tier3: orb keypoints=",
        ),
        (
            "audio",
            fixture::wav16(44_100, &fixture::tone(0xC2, 0.5)),
            "tier3:",
        ),
        ("text", fixture::prose(0xC3, 4096).into_bytes(), "tier3:"),
        ("binary", fixture::binary_blob(0xC4, 64 * 1024), "tier3:"),
    ];
    for (name, bytes, needle) in cases {
        let d = modhash::describe(&bytes).unwrap_or_else(|e| panic!("{name}: {e}"));
        let text = render_description(&d);
        for tier in ["tier1:", "tier2:", "tier3:"] {
            assert!(text.contains(tier), "{name}: output missing {tier}\n{text}");
        }
        assert!(text.contains(needle), "{name}: missing {needle}\n{text}");
    }
}

/// `distance` is the kit's scalar axis: identical inputs score 0, and
/// the text/binary maps are `round((1 - jaccard) * 1e6)`.
#[test]
fn distance_axes_are_scalar() {
    let ta = signature_of(fixture::prose(0xD1, 4096).as_bytes()).unwrap();
    let tb = signature_of(fixture::prose(0xD1, 4096).as_bytes()).unwrap();
    assert_eq!(distance(&ta, &tb).unwrap(), 0, "identical text scores 0");

    let a = signature_of(&fixture::binary_blob(0xD2, 48 * 1024)).unwrap();
    let b = signature_of(&fixture::binary_blob(0xD3, 48 * 1024)).unwrap();
    let d = distance(&a, &b).unwrap();
    assert!(d >= 900_000, "unrelated blobs sit near 1e6, got {d}");

    // Cross-modality distance is a named error, never a silent 0.
    let img = signature_of(&fixture::bmp24(
        8,
        8,
        &fixture::patterned_pixels(0xD4, 8, 8),
    ))
    .unwrap();
    assert!(distance(&img, &ta).is_err());
}
