#!/usr/bin/env python3
"""Deterministic corpus builder for the differential lane.

Copies committed fixtures (smoke + crate test fixtures) and generates
the small synthetic files nothing else provides. No third-party deps —
Pillow-generated images are taken from committed fixtures instead.

Determinism: every generated byte stream derives from a fixed-splitmix
PRNG or a literal recipe, so `build_corpus.sh` run twice is byte-stable
and the corpus is safe to commit.
"""
from __future__ import annotations

import hashlib
import io
import os
import random
import shutil
import struct
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]          # modhash worktree root
HERE = Path(__file__).resolve().parent              # lab/differential/corpus
OUT = HERE                                          # files land beside gen.py

SMOKE = ROOT / "lab" / "smoke-fixtures"
FIX = {
    "modhash": ROOT / "modhash" / "tests" / "fixtures",
    "jpeg": ROOT / "modhash-jpeg" / "tests" / "fixtures",
    "png": ROOT / "modhash-png" / "tests" / "fixtures",
    "bmp": ROOT / "modhash-bmp" / "tests" / "fixtures",
    "video": ROOT / "modhash-video" / "tests" / "fixtures",
    "pdf": ROOT / "modhash-pdf" / "tests" / "fixtures",
    "mp3": ROOT / "modhash-mp3" / "tests" / "fixtures",
}

# ---------------------------------------------------------------- copies
COPIES = [
    # (source, dest-name)
    (SMOKE / "base_444.jpg", "img/base_444.jpg"),
    (SMOKE / "base_444.png", "img/base_444.png"),
    (SMOKE / "phash_rgb8_48x40.png", "img/phash_rgb8_48x40.png"),
    (SMOKE / "p24_top_down.bmp", "img/p24_top_down.bmp"),
    (SMOKE / "blob.bin", "bin/blob.bin"),
    (SMOKE / "minimal.zip", "bin/minimal.zip"),
    (SMOKE / "prose.txt", "text/prose.txt"),
    (SMOKE / "text_page.pdf", "text/text_page.pdf"),
    (SMOKE / "tone.wav", "audio/tone.wav"),
    (SMOKE / "tone.flac", "audio/tone.flac"),
    (SMOKE / "l3_short.mp3", "audio/l3_short.mp3"),
    (SMOKE / "a_64x48.mp4", "video/a_64x48.mp4"),
    (SMOKE / "minimal.mp4", "video/minimal.mp4"),
    # decoders under test
    (FIX["jpeg"] / "prog_420.jpg", "img/prog_420.jpg"),
    (FIX["jpeg"] / "prog_444.jpg", "img/prog_444.jpg"),
    (FIX["jpeg"] / "prog_gray.jpg", "img/prog_gray.jpg"),
    (FIX["jpeg"] / "base_gray.jpg", "img/base_gray.jpg"),
    (FIX["jpeg"] / "base_422.jpg", "img/base_422.jpg"),
    (FIX["png"] / "rgb16_3x2.png", "img/rgb16_3x2.png"),
    (FIX["png"] / "gray16_3x2.png", "img/gray16_3x2.png"),
    (FIX["png"] / "rgba16_2x2.png", "img/rgba16_2x2.png"),
    (FIX["png"] / "adam7_13x11_rgb.png", "img/adam7_13x11_rgb.png"),
    (FIX["bmp"] / "p24_bottom_up.bmp", "img/p24_bottom_up.bmp"),
    (FIX["bmp"] / "rle8.bmp", "img/rle8.bmp"),
    (FIX["bmp"] / "p32_v5_rgb.bmp", "img/p32_v5_rgb.bmp"),
    (FIX["modhash"] / "tone22.wav", "audio/tone22.wav"),
    (FIX["mp3"] / "l3_mono.mp3", "audio/l3_mono.mp3"),
    (FIX["mp3"] / "l3_48k.mp3", "audio/l3_48k.mp3"),
    (FIX["video"] / "a_64x48.mov", "video/a_64x48.mov"),
    (FIX["video"] / "a_128x96.mp4", "video/a_128x96.mp4"),
    (FIX["video"] / "a_crf40.mp4", "video/a_crf40.mp4"),
    (FIX["video"] / "b_64x48.mp4", "video/b_64x48.mp4"),
    (FIX["video"] / "e_mp4v.mp4", "video/e_mp4v.mp4"),
    (FIX["video"] / "high_64x48.mp4", "video/high_64x48.mp4"),
    (FIX["video"] / "a_frag.mp4", "video/a_frag.mp4"),
    (FIX["video"] / "audioonly.mp4", "video/audioonly.mp4"),
    (FIX["pdf"] / "standard_default.pdf", "text/standard_default.pdf"),
    (FIX["pdf"] / "tounicode_bfrange.pdf", "text/tounicode_bfrange.pdf"),
    (FIX["pdf"] / "macroman.pdf", "text/macroman.pdf"),
    (FIX["pdf"] / "encrypted.pdf", "text/encrypted.pdf"),
    (FIX["pdf"] / "objstm.pdf", "text/objstm.pdf"),
]


def _splitmix(seed: int):
    x = seed & 0xFFFFFFFFFFFFFFFF

    def nxt() -> int:
        nonlocal x
        x = (x + 0x9E3779B97F4A7C15) & 0xFFFFFFFFFFFFFFFF
        z = x
        z = ((z ^ (z >> 30)) * 0xBF58476D1CE4E5B9) & 0xFFFFFFFFFFFFFFFF
        z = ((z ^ (z >> 27)) * 0x94D049BB133111EB) & 0xFFFFFFFFFFFFFFFF
        return z ^ (z >> 31)

    return nxt


def _png_write(path: Path, w: int, h: int, rgb_rows: list[bytes]):
    """Minimal 8-bit RGB PNG writer (filter 0 rows)."""
    import zlib

    def chunk(tag: bytes, data: bytes) -> bytes:
        return (struct.pack(">I", len(data)) + tag + data
                + struct.pack(">I", zlib.crc32(tag + data) & 0xFFFFFFFF))

    raw = b"".join(b"\x00" + row for row in rgb_rows)
    ihdr = struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)
    png = (b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", ihdr)
           + chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b""))
    path.write_bytes(png)


def _wav_write(path: Path, samples: list[int], rate: int, sampwidth: int,
               channels: int = 1):
    """PCM WAV writer; samples are Python ints in the container's range."""
    frames = len(samples) // channels
    if sampwidth == 1:
        payload = bytes((s & 0xFF for s in samples))
    elif sampwidth == 2:
        payload = b"".join(struct.pack("<h", s) for s in samples)
    elif sampwidth == 3:
        payload = b"".join(
            struct.pack("<I", s & 0xFFFFFF)[:3] for s in samples)
    else:
        payload = b"".join(struct.pack("<i", s) for s in samples)
    byte_rate = rate * channels * sampwidth
    block = channels * sampwidth
    hdr = (b"fmt " + struct.pack("<IHHIIHH", 16, 1, channels, rate,
                                 byte_rate, block, sampwidth * 8))
    data = b"data" + struct.pack("<I", len(payload)) + payload
    body = b"WAVE" + hdr + data
    path.write_bytes(b"RIFF" + struct.pack("<I", len(body)) + body)


def _gif89(path: Path):
    """Minimal 1x1 GIF89a (literal bytes, public-domain recipe)."""
    path.write_bytes(bytes.fromhex(
        "47494638396101000100800000000000ffffff21f90401000000002c000000"
        "00010001000002024401003b"))


def _docx(path: Path, paragraphs: list[str]):
    """Deterministic .docx: stored members, fixed timestamps/order."""
    content_types = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
        '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
        '<Default Extension="xml" ContentType="application/xml"/>'
        '<Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
        '</Types>')
    rels = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
        '<Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/>'
        '</Relationships>')
    body = "".join(
        f'<w:p><w:r><w:t xml:space="preserve">{p}</w:t></w:r></w:p>'
        for p in paragraphs)
    document = (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
        '<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">'
        f'<w:body>{body}</w:body></w:document>')
    with zipfile.ZipFile(path, "w", zipfile.ZIP_STORED) as z:
        for name, payload in (
            ("[Content_Types].xml", content_types),
            ("_rels/.rels", rels),
            ("word/document.xml", document),
        ):
            zi = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
            zi.compress_type = zipfile.ZIP_STORED
            zi.external_attr = 0o644 << 16
            z.writestr(zi, payload)


def _zip_pair(stored_path: Path, deflated_path: Path, members: dict[str, bytes]):
    for path, method in ((stored_path, zipfile.ZIP_STORED),
                         (deflated_path, zipfile.ZIP_DEFLATED)):
        with zipfile.ZipFile(path, "w", method) as z:
            for name, payload in members.items():
                zi = zipfile.ZipInfo(name, date_time=(2026, 1, 1, 0, 0, 0))
                zi.compress_type = method
                z.writestr(zi, payload)


def _png_big(path: Path, w: int = 1200, h: int = 800):
    nxt = _splitmix(0xB16)
    rows = []
    for y in range(h):
        row = bytearray()
        for x in range(w):
            v = nxt()
            row += bytes(((x * 3 + y) & 0xFF, (v >> 8) & 0xFF, (x + y * 2) & 0xFF))
        rows.append(bytes(row))
    _png_write(path, w, h, rows)


def main() -> int:
    random.seed(20261003)
    manifest_rows: list[tuple[str, str, str]] = []

    for sub in ("img", "audio", "video", "text", "bin", "real"):
        (OUT / sub).mkdir(parents=True, exist_ok=True)

    for src, rel in COPIES:
        dst = OUT / rel
        if not src.exists():
            print(f"MISSING {src}", file=sys.stderr)
            return 1
        shutil.copyfile(src, dst)
        manifest_rows.append((rel, "copy", str(src.relative_to(ROOT))))

    # ------------------------------------------------- generated: images
    _png_big(OUT / "img" / "big_1200x800.png")
    manifest_rows.append(("img/big_1200x800.png", "gen", "splitmix 0xB16 1200x800 RGB8 PNG"))
    _gif89(OUT / "img" / "flat.gif")
    manifest_rows.append(("img/flat.gif", "gen", "literal GIF89a 1x1"))

    # ------------------------------------------------- generated: audio
    nxt = _splitmix(0xA0D10)
    # 440 Hz + 880 Hz stereo, 1 s @ 44100, 16-bit
    import math
    samples = []
    for i in range(44100):
        s = int(12000 * math.sin(2 * math.pi * 440 * i / 44100))
        r = int(8000 * math.sin(2 * math.pi * 880 * i / 44100))
        samples += [s, r]
    _wav_write(OUT / "audio" / "stereo_441.wav", samples, 44100, 2, 2)
    manifest_rows.append(("audio/stereo_441.wav", "gen", "440+880Hz stereo 1s 44.1k i16"))
    # 24-bit mono 0.5 s
    s24 = [int(2_000_000 * math.sin(2 * math.pi * 220 * i / 44100))
           for i in range(22050)]
    _wav_write(OUT / "audio" / "wav24.wav", s24, 44100, 3, 1)
    manifest_rows.append(("audio/wav24.wav", "gen", "220Hz mono 0.5s 44.1k i24"))
    # 8-bit mono
    s8 = [128 + int(80 * math.sin(2 * math.pi * 330 * i / 22050))
          for i in range(11025)]
    _wav_write(OUT / "audio" / "wav8_22k.wav", s8, 22050, 1, 1)
    manifest_rows.append(("audio/wav8_22k.wav", "gen", "330Hz mono 0.5s 22.05k u8"))
    _ = nxt  # keep PRNG consumption documented

    # ------------------------------------------------- generated: text
    vi_comp = "Tầng thứ nhất kiểm chứng bằng băm chính xác.\n" * 3
    vi_decomp = "Tầng thứ nhất kiểm chứng bằng băm chính xác.\n" * 3
    (OUT / "text" / "vi_nfc.txt").write_text(vi_comp, encoding="utf-8")
    (OUT / "text" / "vi_nfd.txt").write_text(vi_decomp, encoding="utf-8")
    manifest_rows += [
        ("text/vi_nfc.txt", "gen", "composed vietnamese x3"),
        ("text/vi_nfd.txt", "gen", "decomposed vietnamese x3"),
    ]
    (OUT / "text" / "punct_tags.txt").write_text(
        '<p class="x">Hello, World! This is a tag-stripped "sample" — '
        'with em-dash, ellipsis… and CRLF.\r\n' * 4, encoding="utf-8")
    manifest_rows.append(("text/punct_tags.txt", "gen", "html+punct+crlf"))
    (OUT / "text" / "short_two.txt").write_text("hai từ\n", encoding="utf-8")
    manifest_rows.append(("text/short_two.txt", "gen", "2-word doc: rust shingles, py empty"))

    text_a = " ".join(
        f"câu {i} với nội dung mô tả sản phẩm và tiêu đề lặp"
        for i in range(60)) + "\n"
    text_a_edit = text_a.replace("câu 30", "câu ba mươi đã sửa")
    text_b = " ".join(
        f"đoạn {i} hoàn toàn khác về chủ đề và từ vựng"
        for i in range(60)) + "\n"
    (OUT / "text" / "doc_a.txt").write_text(text_a, encoding="utf-8")
    (OUT / "text" / "doc_a_edit.txt").write_text(text_a_edit, encoding="utf-8")
    (OUT / "text" / "doc_b.txt").write_text(text_b, encoding="utf-8")
    manifest_rows += [
        ("text/doc_a.txt", "gen", "60-phrase doc"),
        ("text/doc_a_edit.txt", "gen", "doc_a with 1 phrase changed"),
        ("text/doc_b.txt", "gen", "different 60-phrase doc"),
    ]

    # ------------------------------------------------- generated: binary
    nxt = _splitmix(0xDEADBEEFCAFEF00D)
    blob = bytes((nxt() & 0xFF) for _ in range(400_000))
    (OUT / "bin" / "f_a.bin").write_bytes(blob)
    (OUT / "bin" / "f_copy.bin").write_bytes(blob)
    mod = bytearray(blob)
    mod[100_000:100_000] = b"\x55"          # 1-byte insert at 25%
    (OUT / "bin" / "f_mod.bin").write_bytes(bytes(mod))
    (OUT / "bin" / "f_tail.bin").write_bytes(blob[:360_000])  # cut 10% tail
    nxt2 = _splitmix(0x0123456789ABCDEF)
    (OUT / "bin" / "f_other.bin").write_bytes(
        bytes((nxt2() & 0xFF) for _ in range(400_000)))
    manifest_rows += [
        ("bin/f_a.bin", "gen", "splitmix DEADBEEFCAFEF00D 400KB"),
        ("bin/f_copy.bin", "gen", "byte copy of f_a"),
        ("bin/f_mod.bin", "gen", "f_a + 1-byte insert @100K"),
        ("bin/f_tail.bin", "gen", "f_a minus last 40KB"),
        ("bin/f_other.bin", "gen", "splitmix 0123456789ABCDEF 400KB"),
    ]

    _docx(OUT / "bin" / "hello.docx",
          ["Differential lane document.", "Hai đoạn văn thứ hai."])
    manifest_rows.append(("bin/hello.docx", "gen", "docx stored, 2 paragraphs"))
    _zip_pair(OUT / "bin" / "pack_stored.zip", OUT / "bin" / "pack_deflated.zip",
              {"a.txt": b"alpha content " * 40,
               "dir/b.bin": blob[:50_000],
               "empty.txt": b""})
    manifest_rows += [
        ("bin/pack_stored.zip", "gen", "same members, stored"),
        ("bin/pack_deflated.zip", "gen", "same members, deflated"),
    ]

    # ------------------------------------------------- real files (arena)
    arena = os.environ.get("ARENA_WS",
        "C:/Users/n24q02m-wpc/projects/.audit-hashkit-290926/arena_ws")
    arena = Path(arena)
    real_srcs = [
        (arena / "lab/datasets/real-check/tep/img_a.png", "real/img_a.png"),
        (arena / "lab/datasets/real-check/tep/img_b.jpg", "real/img_b.jpg"),
        (arena / "lab/datasets/real-check/tep/img_other.png", "real/img_other.png"),
        (arena / "lab/datasets/real-check/tep/audio_a.wav", "real/audio_a.wav"),
        (arena / "lab/datasets/real-check/tep/audio_a_quiet.wav",
         "real/audio_a_quiet.wav"),
        (arena / "lab/datasets/real-check/tep/text_a.txt", "real/text_a.txt"),
        (arena / "lab/datasets/real-check/tep/text_a_edit.txt",
         "real/text_a_edit.txt"),
        (arena / "lab/datasets/real-check/tep/text_b.txt", "real/text_b.txt"),
        (arena / "lab/datasets/real-check/tep/v_clip.avi", "real/v_clip.avi"),
        (arena / "lab/datasets/image-search/portrait-close-up-human-face-person-stud-1.jpg",
         "real/portrait_1.jpg"),
        (arena / "lab/datasets/image-search/city-street-architecture-buildings-photo-1.jpg",
         "real/city_1.jpg"),
    ]
    for src, rel in real_srcs:
        dst = OUT / rel
        if src.exists():
            shutil.copyfile(src, dst)
            manifest_rows.append((rel, "copy-external", str(src)))
        else:
            manifest_rows.append((rel, "missing-skip", str(src)))

    # ------------------------------------------------- manifest + pairs
    manifest = OUT / "manifest.tsv"
    with manifest.open("w", newline="") as f:
        f.write("file\torigin\tsource\tsha256\tbytes\n")
        for rel, origin, source in sorted(manifest_rows):
            p = OUT / rel
            if p.exists():
                data = p.read_bytes()
                f.write(f"{rel}\t{origin}\t{source}\t"
                        f"{hashlib.sha256(data).hexdigest()}\t{len(data)}\n")
            else:
                f.write(f"{rel}\t{origin}\t{source}\t-\t-\n")

    pairs = [
        # same content, different container/encoding
        ("img/base_444.png", "img/base_444.jpg", "same-pixels png/jpg"),
        ("img/p24_top_down.bmp", "img/p24_bottom_up.bmp", "same? bmp orientation"),
        ("audio/tone.wav", "audio/tone.flac", "same pcm two containers"),
        ("audio/l3_short.mp3", "audio/l3_mono.mp3", "related? mp3 variants"),
        ("audio/stereo_441.wav", "audio/stereo_441.wav", "self audio"),
        ("video/a_64x48.mp4", "video/a_64x48.mov", "same stream mp4/mov"),
        ("video/a_64x48.mp4", "video/a_128x96.mp4", "same content 2x scale"),
        ("video/a_64x48.mp4", "video/a_crf40.mp4", "reencode crf40"),
        ("video/a_64x48.mp4", "video/b_64x48.mp4", "different content"),
        ("bin/pack_stored.zip", "bin/pack_deflated.zip", "same members diff method"),
        ("bin/f_a.bin", "bin/f_copy.bin", "identical"),
        ("bin/f_a.bin", "bin/f_mod.bin", "1-byte insert"),
        ("bin/f_a.bin", "bin/f_tail.bin", "10% tail cut"),
        ("bin/f_a.bin", "bin/f_other.bin", "unrelated"),
        ("text/doc_a.txt", "text/doc_a_edit.txt", "1-phrase edit"),
        ("text/doc_a.txt", "text/doc_b.txt", "unrelated text"),
        ("text/vi_nfc.txt", "text/vi_nfd.txt", "nfc/nfd same text"),
        ("text/text_page.pdf", "text/standard_default.pdf", "same pdf two files"),
        ("real/img_a.png", "real/img_b.jpg", "real same-content png/jpg"),
        ("real/img_a.png", "real/img_other.png", "real different images"),
        ("real/audio_a.wav", "real/audio_a_quiet.wav", "real quiet variant"),
        ("real/text_a.txt", "real/text_a_edit.txt", "real text edit"),
        ("real/text_a.txt", "real/text_b.txt", "real different text"),
    ]
    with (OUT / "pairs.tsv").open("w", newline="") as f:
        f.write("a\tb\tnote\n")
        for a, b, note in pairs:
            f.write(f"{a}\t{b}\t{note}\n")

    n = sum(1 for p in OUT.rglob("*") if p.is_file()
            and p.name not in {"gen.py", "manifest.tsv", "pairs.tsv"})
    print(f"corpus: {n} files -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
